package spring.dynamodb.awsdynamodbcrud.dynamoTables;

import com.amazonaws.services.dynamodbv2.datamodeling.*;


@DynamoDBTable(tableName = "movie_prod_table")
public class MovieProd {
        @DynamoDBHashKey(attributeName = "movie_id")
        @DynamoDBAutoGeneratedKey
        String movieId;
        @DynamoDBAttribute(attributeName = "Director")
        String director;

        public String getMovieId() {
                return movieId;
        }

        public String getDirector() {
                return director;
        }

        public void setMovieId(String movieId) {
                this.movieId = movieId;
        }

        public void setDirector(String director) {
                this.director = director;
        }
}




